name: Flutter Web

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

   steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Shell Script
        run: |
          cd build/web
          git init
          git config --global user.email joaovfranca1@gmail.com.com
          git config --global user.name João Victor de França
          chmod +x deploy.sh
          ./deploy.sh